package org.shankaa.coworkers.stubs
{
	import flash.system.Worker;
	import flash.utils.ByteArray;
	
	import org.as3.ms.xls.ExcelFile;

	/**
	 * 
	 * @author Hugues Sansen, Shankaa
	 * 
	 * Coworker is provided under the European Union Public Licence (EUPL)
	 */
	public class Stub_ExcelFile extends Stub
	{
		/**
		 * creates a new ExcelFile() on remote worker
		 *  
		 * @param worker
		 * 
		 */
		public function Stub_ExcelFile(remoteWorker:Worker)
		{
			super(remoteWorker,ExcelFile);
		}
		
		/**
		 * 
		 * 
		 *  
		 * @param onCallback 	function(event:Event) where event.CurrentTarget is a MessageChannel receiving the resulting ExcelFile
		 * @param onEvent		function(event:Event) where event.CurrentTarget is a MessageChannel receiving the events generated by the loadFromByteArrayInWorker function
		 * @param xls			the byteArray stream to load in the excelfile
		 * 
		 */
		public function loadFromByteArray(onCallback:Function,onEvent:Function,xls:ByteArray,fileExtension:String):void{
			applyOnRemote("loadFromByteArray"+INWORKERSUFFIX,onCallback,onEvent,xls,fileExtension);
		}
		
	}
}